# Generated by Django 3.1.4 on 2020-12-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_auto_20201216_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Cover Photo'),
        ),
    ]
