# Generated by Django 3.1.4 on 2020-12-22 18:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0006_auto_20201223_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='publish',
            field=models.DateField(default=datetime.datetime(2020, 12, 22, 18, 36, 9, 220655, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
