# Generated by Django 3.1.4 on 2020-12-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0007_blog_publish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-publish', '-update_date']},
        ),
    ]
