# Generated by Django 3.1.4 on 2020-12-23 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0008_auto_20201223_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlikes',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='commentlikes',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CommentLikes',
        ),
    ]
