# Generated by Django 3.1.4 on 2020-12-23 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0010_auto_20201223_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-publish', '-update_date'], 'verbose_name': 'blog'},
        ),
    ]
