# Generated by Django 3.1.4 on 2020-12-24 18:55

import app_blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0011_auto_20201224_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(default='None/cover_image.jpg', upload_to=app_blog.models.upload_location, verbose_name='Cover Photo'),
        ),
    ]
